### ISSUE TITLE
Empty $dokuparams & Invoice ID Not Found

### ISSUE THREAD

**Issue by saemul** [PTNUSASATUINTIARTHA-DOKU/WHMCS-DOKU#2]
Your Mall Id: 10366286
What WHMCS Version: 7.2.3
What kind of issues and/or trouble you faced

Empty $dokuparams ( Get from Gateway Logs)
Debut Data:
PAYMENTDATETIME => 
PURCHASECURRENCY => 
LIABILITY => 
PAYMENTCHANNEL => 
AMOUNT => 
PAYMENTCODE => 
MCN => 
WORDS => 
RESULTMSG => 
VERIFYID => 
TRANSIDMERCHANT => 
BANK => 
STATUSTYPE => 
APPROVALCODE => 
EDUSTATUS => 
THREEDSECURESTATUS => 
VERIFYSCORE => 
CURRENCY => 
RESPONSECODE => 
CHNAME => 
BRAND => 
VERIFYSTATUS => 
SESSIONID => 
STATUSCODE =>

Result:
Payment Redirect From Doku

/callback/dokuhosted.php failing with error message:

Debug Data:
page => redirect 

Result:
Invoice ID Not Found

**Comment by aryoprakarsa** [comment]
Hi @saemul, If i saw your result error that your callback seems invalid url because it said Invoice ID Not Found
